name: LeetCode 
on: 
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: imgs/metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: CyberDJ
          plugin_leetcode_sections: solved, skills, recent
