name: RSS_feed
on: 
  schedule:
    - cron: '6 * * * *'
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: News from hackernews
        uses: lowlighter/metrics@latest
        with:
          filename: imgs/metrics.plugin.rss.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4